CREATE TABLE IF NOT EXISTS `tripdb`.`viaggio` (
  `IdViaggio` int unsigned NOT NULL AUTO_INCREMENT,
  `TourAssociato` varchar(45) not null,
  `Conducente` varchar(45),
  `Accompagnatrice` varchar(45) default null,
  `TargaMezzoImpiegato` varchar(10),
  `DataPartenzaViaggio` date NOT NULL,
  `DataRitornoViaggio` date NOT NULL, 
  `CostoDelViaggio` decimal(8,2) NOT NULL,
  `NumeroKm` int unsigned NOT NULL,
  `PostiDisponibili` int unsigned NOT NULL,
  `DataCancellazione` date DEFAULT NULL,
  PRIMARY KEY (`idviaggio`),
  KEY `FK_TourAssocciato_idx` (`TourAssociato`),
  KEY `FK_Conducente_idx` (`Conducente`),
  KEY `FK_Accompagnatrice_idx`(`Accompagnatrice`),
  KEY `FK_Mezzoimpiegato_idx` (`TargaMezzoImpiegato`),
  CONSTRAINT `FK_Accompagnatrice` FOREIGN KEY (`Accompagnatrice`) REFERENCES `dipendente` (`EmailDipendente`)on delete set null,
  CONSTRAINT `FK_Conducente` FOREIGN KEY (`Conducente`) REFERENCES `dipendente` (`EmailDipendente`)on delete set null,
  CONSTRAINT `FK_Mezzoimpiegato` FOREIGN KEY (`TargaMezzoImpiegato`) REFERENCES `mezzo` (`Targa`) on delete set null,
  CONSTRAINT `FK_TourAssocciato` FOREIGN KEY (`TourAssociato`) REFERENCES `tour` (`DenominazioneTour`) on delete cascade,
  CONSTRAINT `DataRitornoViaggioCannotBeLesserThanDataPartenzaViaggio` CHECK ((`DataRitornoViaggio` IS NULL) OR (`DataPartenzaViaggio` IS NULL AND `DataRitornoViaggio` IS NULL) OR (`DataRitornoViaggio` >= `DataPartenzaViaggio`))
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE = utf8mb4_general_ci;
