DELETE FROM `tripdb`.`prenotazione`;
INSERT INTO `tripdb`.`prenotazione` 
(
  `ClientePrenotante`,
  `DataDiPrenotazione`,  
  `ViaggioAssociato`,
  `NumeroDiPostiPrenotati`,
  `DataDiConferma`, 
  `DataSaldo`)
VALUES
('gdn@mail.com',
  '2022-07-09',
  '1',
  '6',
  NULL, 
  NULL
 );
 INSERT INTO `tripdb`.`prenotazione` 
(
    `ClientePrenotante`,
  `DataDiPrenotazione`, 
  `ViaggioAssociato`,
  `NumeroDiPostiPrenotati`,
  `DataDiConferma`, 
  `DataSaldo`)
VALUES
('ldn@mail.com',
  '2022-07-09',
  '1',
  '4',
   NULL,
   NULL
 );
 INSERT INTO `tripdb`.`prenotazione` 
(
    `ClientePrenotante`,
  `DataDiPrenotazione`, 
  `ViaggioAssociato`,
  `NumeroDiPostiPrenotati`,
  `DataDiConferma`, 
  `DataSaldo`)
VALUES
('gvnn@mail.com',
  '2022-07-09',
  '1',
  '5',
   NULL,
   NULL
 );
INSERT INTO `tripdb`.`prenotazione` 
(
    `ClientePrenotante`,
  `DataDiPrenotazione`, 
  `ViaggioAssociato`,
  `NumeroDiPostiPrenotati`,
  `DataDiConferma`, 
  `DataSaldo`)
VALUES
('smn@mail.com',
  '2022-07-09',
  '2',
  '2',
   NULL,
   NULL
 );
INSERT INTO `tripdb`.`prenotazione` 
(
    `ClientePrenotante`,
  `DataDiPrenotazione`, 
  `ViaggioAssociato`,
  `NumeroDiPostiPrenotati`,
  `DataDiConferma`, 
  `DataSaldo`)
VALUES
('gdn@mail.com',
  '2022-07-09',
  '2',
  '1',
  NULL, 
  NULL
 );
 INSERT INTO `tripdb`.`prenotazione` 
(
    `ClientePrenotante`,
  `DataDiPrenotazione`, 
  `ViaggioAssociato`,
  `NumeroDiPostiPrenotati`,
  `DataDiConferma`, 
  `DataSaldo`)
VALUES
('ldn@mail.com',
  '2022-07-09',
  '2',
  '2',
   NULL,
   NULL
 );
 INSERT INTO `tripdb`.`prenotazione` 
(
    `ClientePrenotante`,
  `DataDiPrenotazione`, 
  `ViaggioAssociato`,
  `NumeroDiPostiPrenotati`,
  `DataDiConferma`, 
  `DataSaldo`)
VALUES
('gvnn@mail.com',
  '2022-07-09',
  '2',
  '1',
   NULL,
   NULL
 );
INSERT INTO `tripdb`.`prenotazione` 
(
    `ClientePrenotante`,
  `DataDiPrenotazione`, 
  `ViaggioAssociato`,
  `NumeroDiPostiPrenotati`,
  `DataDiConferma`, 
  `DataSaldo`)
VALUES
('smn@mail.com',
  '2022-07-09',
  '3',
  '12',
   NULL,
   NULL
 );